name: dynamo_json_decoder
description: "A Flutter project that decodes serialized JSON strings into Flutter collection objects."

version: 1.0.0

repository: https://github.com/patushie/dynamo_json_decoder
homepage: https://github.com/patushie/dynamo_json_decoder
issue_tracker: https://github.com/patushie/dynamo_json_decoder/issues

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.4.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
