name: dynamo_json_decoder
description: "A Flutter project that decodes serialized JSON strings into Flutter collection objects."

version: 1.0.0

environment:
  sdk: ^3.6.0-334.3.beta

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.4.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
